// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "./client";
import type {
  AuthJwtLoginData,
  AuthJwtLoginResponses,
  AuthJwtLoginErrors,
  AuthJwtLogoutData,
  AuthJwtLogoutResponses,
  AuthJwtLogoutErrors,
  RegisterRegisterData,
  RegisterRegisterResponses,
  RegisterRegisterErrors,
  ResetForgotPasswordData,
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ResetResetPasswordData,
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  VerifyRequestTokenData,
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  VerifyVerifyData,
  VerifyVerifyResponses,
  VerifyVerifyErrors,
  UsersCurrentUserData,
  UsersCurrentUserResponses,
  UsersCurrentUserErrors,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUserData,
  UsersUserResponses,
  UsersUserErrors,
  UsersPatchUserData,
  UsersPatchUserResponses,
  UsersPatchUserErrors,
  RequestVerificationCodeData,
  RequestVerificationCodeResponses,
  RequestVerificationCodeErrors,
  ConfirmVerificationCodeData,
  ConfirmVerificationCodeResponses,
  ConfirmVerificationCodeErrors,
  LoginData,
  LoginResponses,
  LoginErrors,
  TwoFactorLoginData,
  TwoFactorLoginResponses,
  TwoFactorLoginErrors,
  EnrollTotpData,
  EnrollTotpResponses,
  EnableTotpData,
  EnableTotpResponses,
  EnableTotpErrors,
  DisableTotpData,
  DisableTotpResponses,
  DisableTotpErrors,
  ListRulesData,
  ListRulesResponses,
  CreateRuleData,
  CreateRuleResponses,
  CreateRuleErrors,
  DeleteRuleData,
  DeleteRuleResponses,
  DeleteRuleErrors,
  ListExceptionsData,
  ListExceptionsResponses,
  CreateExceptionData,
  CreateExceptionResponses,
  CreateExceptionErrors,
  DeleteExceptionData,
  DeleteExceptionResponses,
  DeleteExceptionErrors,
  PreviewSlotsData,
  PreviewSlotsResponses,
  PreviewSlotsErrors,
  ListAppointmentsData,
  ListAppointmentsResponses,
  ListAppointmentsErrors,
  CreateAppointmentData,
  CreateAppointmentResponses,
  CreateAppointmentErrors,
  DeleteAppointmentData,
  DeleteAppointmentResponses,
  DeleteAppointmentErrors,
  GetAppointmentData,
  GetAppointmentResponses,
  GetAppointmentErrors,
  UpdateAppointmentData,
  UpdateAppointmentResponses,
  UpdateAppointmentErrors,
  ListContactsData,
  ListContactsResponses,
  CreateContactData,
  CreateContactResponses,
  CreateContactErrors,
  DeleteContactData,
  DeleteContactResponses,
  DeleteContactErrors,
  UpdateContactData,
  UpdateContactResponses,
  UpdateContactErrors,
  GetMyProfileData,
  GetMyProfileResponses,
  UpdateMyProfileData,
  UpdateMyProfileResponses,
  UpdateMyProfileErrors,
  GetThemeData,
  GetThemeResponses,
  UpdateThemeData,
  UpdateThemeResponses,
  UpdateThemeErrors,
  GetPublicArtistData,
  GetPublicArtistResponses,
  GetPublicArtistErrors,
  GetPublicPortfolioData,
  GetPublicPortfolioResponses,
  GetPublicPortfolioErrors,
  GetPublicProductsData,
  GetPublicProductsResponses,
  GetPublicProductsErrors,
  CheckoutData,
  CheckoutResponses,
  CheckoutErrors,
  GetPublicFlashData,
  GetPublicFlashResponses,
  GetPublicFlashErrors,
  GetPublicSlotsData,
  GetPublicSlotsResponses,
  GetPublicSlotsErrors,
  BookData,
  BookResponses,
  BookErrors,
  ClerkMeData,
  ClerkMeResponses,
  ClerkSyncData,
  ClerkSyncResponses,
  ClerkSyncErrors,
  UploadImageData,
  UploadImageResponses,
  UploadImageErrors,
  ListPortfolioData,
  ListPortfolioResponses,
  CreatePortfolioImageData,
  CreatePortfolioImageResponses,
  CreatePortfolioImageErrors,
  DeletePortfolioImageData,
  DeletePortfolioImageResponses,
  DeletePortfolioImageErrors,
  ListFlashData,
  ListFlashResponses,
  CreateFlashData,
  CreateFlashResponses,
  CreateFlashErrors,
  DeleteFlashData,
  DeleteFlashResponses,
  DeleteFlashErrors,
  UpdateFlashData,
  UpdateFlashResponses,
  UpdateFlashErrors,
  ListProductsData,
  ListProductsResponses,
  CreateProductData,
  CreateProductResponses,
  CreateProductErrors,
  DeleteProductData,
  DeleteProductResponses,
  DeleteProductErrors,
  UpdateProductData,
  UpdateProductResponses,
  UpdateProductErrors,
  GetLayoutData,
  GetLayoutResponses,
  UpdateLayoutData,
  UpdateLayoutResponses,
  UpdateLayoutErrors,
  ListCampaignsData,
  ListCampaignsResponses,
  CreateCampaignData,
  CreateCampaignResponses,
  CreateCampaignErrors,
  DeleteCampaignData,
  DeleteCampaignResponses,
  DeleteCampaignErrors,
  ReportIssueData,
  ReportIssueResponses,
  ReportIssueErrors,
  ReadItemData,
  ReadItemResponses,
  ReadItemErrors,
  CreateItemData,
  CreateItemResponses,
  CreateItemErrors,
  DeleteItemData,
  DeleteItemResponses,
  DeleteItemErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/logout",
    ...options,
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Request Verification Code
 */
export const requestVerificationCode = <ThrowOnError extends boolean = false>(
  options: Options<RequestVerificationCodeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RequestVerificationCodeResponses,
    RequestVerificationCodeErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verification-code",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Confirm Verification Code
 */
export const confirmVerificationCode = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmVerificationCodeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ConfirmVerificationCodeResponses,
    ConfirmVerificationCodeErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/confirm-verification-code",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginResponses,
    LoginErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Two Factor Login
 */
export const twoFactorLogin = <ThrowOnError extends boolean = false>(
  options: Options<TwoFactorLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TwoFactorLoginResponses,
    TwoFactorLoginErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/2fa/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Enroll Totp
 */
export const enrollTotp = <ThrowOnError extends boolean = false>(
  options?: Options<EnrollTotpData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    EnrollTotpResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/2fa/enroll",
    ...options,
  });
};

/**
 * Enable Totp
 */
export const enableTotp = <ThrowOnError extends boolean = false>(
  options: Options<EnableTotpData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    EnableTotpResponses,
    EnableTotpErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/2fa/enable",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Disable Totp
 */
export const disableTotp = <ThrowOnError extends boolean = false>(
  options: Options<DisableTotpData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    DisableTotpResponses,
    DisableTotpErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/2fa/disable",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Rules
 */
export const listRules = <ThrowOnError extends boolean = false>(
  options?: Options<ListRulesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListRulesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/rules",
    ...options,
  });
};

/**
 * Create Rule
 */
export const createRule = <ThrowOnError extends boolean = false>(
  options: Options<CreateRuleData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateRuleResponses,
    CreateRuleErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/rules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Rule
 */
export const deleteRule = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRuleData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteRuleResponses,
    DeleteRuleErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/rules/{rule_id}",
    ...options,
  });
};

/**
 * List Exceptions
 */
export const listExceptions = <ThrowOnError extends boolean = false>(
  options?: Options<ListExceptionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListExceptionsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/exceptions",
    ...options,
  });
};

/**
 * Create Exception
 */
export const createException = <ThrowOnError extends boolean = false>(
  options: Options<CreateExceptionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateExceptionResponses,
    CreateExceptionErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/exceptions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Exception
 */
export const deleteException = <ThrowOnError extends boolean = false>(
  options: Options<DeleteExceptionData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteExceptionResponses,
    DeleteExceptionErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/exceptions/{exception_id}",
    ...options,
  });
};

/**
 * Preview Slots
 * Bookable slots for the artist on a date (same engine as public booking).
 */
export const previewSlots = <ThrowOnError extends boolean = false>(
  options: Options<PreviewSlotsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    PreviewSlotsResponses,
    PreviewSlotsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/availability/slots",
    ...options,
  });
};

/**
 * List Appointments
 */
export const listAppointments = <ThrowOnError extends boolean = false>(
  options: Options<ListAppointmentsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ListAppointmentsResponses,
    ListAppointmentsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/appointments/",
    ...options,
  });
};

/**
 * Create Appointment
 */
export const createAppointment = <ThrowOnError extends boolean = false>(
  options: Options<CreateAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateAppointmentResponses,
    CreateAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/appointments/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Appointment
 */
export const deleteAppointment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteAppointmentResponses,
    DeleteAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/appointments/{appointment_id}",
    ...options,
  });
};

/**
 * Get Appointment
 */
export const getAppointment = <ThrowOnError extends boolean = false>(
  options: Options<GetAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAppointmentResponses,
    GetAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/appointments/{appointment_id}",
    ...options,
  });
};

/**
 * Update Appointment
 */
export const updateAppointment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateAppointmentResponses,
    UpdateAppointmentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/appointments/{appointment_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Contacts
 */
export const listContacts = <ThrowOnError extends boolean = false>(
  options?: Options<ListContactsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListContactsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/contacts/",
    ...options,
  });
};

/**
 * Create Contact
 */
export const createContact = <ThrowOnError extends boolean = false>(
  options: Options<CreateContactData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateContactResponses,
    CreateContactErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/contacts/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Contact
 */
export const deleteContact = <ThrowOnError extends boolean = false>(
  options: Options<DeleteContactData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteContactResponses,
    DeleteContactErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/contacts/{contact_id}",
    ...options,
  });
};

/**
 * Update Contact
 */
export const updateContact = <ThrowOnError extends boolean = false>(
  options: Options<UpdateContactData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateContactResponses,
    UpdateContactErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/contacts/{contact_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get My Profile
 */
export const getMyProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetMyProfileData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMyProfileResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/profile/me",
    ...options,
  });
};

/**
 * Update My Profile
 */
export const updateMyProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMyProfileData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateMyProfileResponses,
    UpdateMyProfileErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/profile/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Theme
 */
export const getTheme = <ThrowOnError extends boolean = false>(
  options?: Options<GetThemeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetThemeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/profile/theme",
    ...options,
  });
};

/**
 * Update Theme
 */
export const updateTheme = <ThrowOnError extends boolean = false>(
  options: Options<UpdateThemeData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateThemeResponses,
    UpdateThemeErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/profile/theme",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Public Artist
 */
export const getPublicArtist = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicArtistData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPublicArtistResponses,
    GetPublicArtistErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}",
    ...options,
  });
};

/**
 * Get Public Portfolio
 */
export const getPublicPortfolio = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicPortfolioData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPublicPortfolioResponses,
    GetPublicPortfolioErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}/portfolio",
    ...options,
  });
};

/**
 * Get Public Products
 */
export const getPublicProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicProductsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPublicProductsResponses,
    GetPublicProductsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}/products",
    ...options,
  });
};

/**
 * Checkout
 */
export const checkout = <ThrowOnError extends boolean = false>(
  options: Options<CheckoutData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CheckoutResponses,
    CheckoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}/checkout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Public Flash
 */
export const getPublicFlash = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicFlashData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPublicFlashResponses,
    GetPublicFlashErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}/flash",
    ...options,
  });
};

/**
 * Get Public Slots
 */
export const getPublicSlots = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicSlotsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPublicSlotsResponses,
    GetPublicSlotsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}/slots",
    ...options,
  });
};

/**
 * Book
 */
export const book = <ThrowOnError extends boolean = false>(
  options: Options<BookData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    BookResponses,
    BookErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/public/artists/{slug}/book",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Clerk Me
 */
export const clerkMe = <ThrowOnError extends boolean = false>(
  options?: Options<ClerkMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ClerkMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/clerk/me",
    ...options,
  });
};

/**
 * Clerk Sync
 * Enrich the local record with the real Clerk email/name (idempotent).
 */
export const clerkSync = <ThrowOnError extends boolean = false>(
  options: Options<ClerkSyncData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ClerkSyncResponses,
    ClerkSyncErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/clerk/sync",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Upload Image
 */
export const uploadImage = <ThrowOnError extends boolean = false>(
  options: Options<UploadImageData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadImageResponses,
    UploadImageErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    url: "/uploads/image",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * List Portfolio
 */
export const listPortfolio = <ThrowOnError extends boolean = false>(
  options?: Options<ListPortfolioData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListPortfolioResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/portfolio/",
    ...options,
  });
};

/**
 * Create Portfolio Image
 */
export const createPortfolioImage = <ThrowOnError extends boolean = false>(
  options: Options<CreatePortfolioImageData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreatePortfolioImageResponses,
    CreatePortfolioImageErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/portfolio/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Portfolio Image
 */
export const deletePortfolioImage = <ThrowOnError extends boolean = false>(
  options: Options<DeletePortfolioImageData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeletePortfolioImageResponses,
    DeletePortfolioImageErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/portfolio/{image_id}",
    ...options,
  });
};

/**
 * List Flash
 */
export const listFlash = <ThrowOnError extends boolean = false>(
  options?: Options<ListFlashData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListFlashResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/flash/",
    ...options,
  });
};

/**
 * Create Flash
 */
export const createFlash = <ThrowOnError extends boolean = false>(
  options: Options<CreateFlashData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateFlashResponses,
    CreateFlashErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/flash/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Flash
 */
export const deleteFlash = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFlashData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteFlashResponses,
    DeleteFlashErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/flash/{piece_id}",
    ...options,
  });
};

/**
 * Update Flash
 */
export const updateFlash = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFlashData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateFlashResponses,
    UpdateFlashErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/flash/{piece_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Products
 */
export const listProducts = <ThrowOnError extends boolean = false>(
  options?: Options<ListProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListProductsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/products/",
    ...options,
  });
};

/**
 * Create Product
 */
export const createProduct = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateProductResponses,
    CreateProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/products/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Product
 */
export const deleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductResponses,
    DeleteProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/products/{product_id}",
    ...options,
  });
};

/**
 * Update Product
 */
export const updateProduct = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProductData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateProductResponses,
    UpdateProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/products/{product_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Layout
 */
export const getLayout = <ThrowOnError extends boolean = false>(
  options?: Options<GetLayoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetLayoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/booking-page/",
    ...options,
  });
};

/**
 * Update Layout
 */
export const updateLayout = <ThrowOnError extends boolean = false>(
  options: Options<UpdateLayoutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateLayoutResponses,
    UpdateLayoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/booking-page/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Campaigns
 */
export const listCampaigns = <ThrowOnError extends boolean = false>(
  options?: Options<ListCampaignsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListCampaignsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/campaigns/",
    ...options,
  });
};

/**
 * Create Campaign
 */
export const createCampaign = <ThrowOnError extends boolean = false>(
  options: Options<CreateCampaignData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateCampaignResponses,
    CreateCampaignErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/campaigns/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Campaign
 */
export const deleteCampaign = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCampaignData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteCampaignResponses,
    DeleteCampaignErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/campaigns/{campaign_id}",
    ...options,
  });
};

/**
 * Report Issue
 */
export const reportIssue = <ThrowOnError extends boolean = false>(
  options: Options<ReportIssueData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ReportIssueResponses,
    ReportIssueErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/issues/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: Options<ReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponses,
    ReadItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/",
    ...options,
  });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateItemResponses,
    CreateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemResponses,
    DeleteItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{item_id}",
    ...options,
  });
};
