// This file is auto-generated by @hey-api/openapi-ts

/**
 * AppointmentCreate
 * Artist manually entering an appointment.
 */
export type AppointmentCreate = {
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Client Name
   */
  client_name: string;
  /**
   * Client Phone
   */
  client_phone?: string | null;
  /**
   * Client Email
   */
  client_email?: string | null;
  /**
   * Client Instagram
   */
  client_instagram?: string | null;
  /**
   * Size
   */
  size?: string | null;
  /**
   * Placement
   */
  placement?: string | null;
  color_type?: ColorType | null;
  /**
   * Subject
   */
  subject?: string | null;
  /**
   * Accommodations Notes
   */
  accommodations_notes?: string | null;
  /**
   * Has Guests
   */
  has_guests?: boolean;
  /**
   * Guests Notes
   */
  guests_notes?: string | null;
  /**
   * Deposit Cents
   */
  deposit_cents?: number;
  /**
   * Booth Id
   */
  booth_id?: string | null;
  /**
   * Buffer Before Minutes
   */
  buffer_before_minutes?: number;
  /**
   * Buffer After Minutes
   */
  buffer_after_minutes?: number;
};

/**
 * AppointmentRead
 */
export type AppointmentRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
  /**
   * Contact Id
   */
  contact_id?: string | null;
  /**
   * Client User Id
   */
  client_user_id?: string | null;
  /**
   * Booth Id
   */
  booth_id?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
  status: AppointmentStatus;
  source: AppointmentSource;
  /**
   * Size
   */
  size?: string | null;
  /**
   * Placement
   */
  placement?: string | null;
  color_type?: ColorType | null;
  /**
   * Subject
   */
  subject?: string | null;
  /**
   * Accommodations Notes
   */
  accommodations_notes?: string | null;
  /**
   * Has Guests
   */
  has_guests: boolean;
  /**
   * Guests Notes
   */
  guests_notes?: string | null;
  /**
   * Client Name
   */
  client_name?: string | null;
  /**
   * Client Email
   */
  client_email?: string | null;
  /**
   * Client Phone
   */
  client_phone?: string | null;
  /**
   * Deposit Cents
   */
  deposit_cents: number;
};

/**
 * AppointmentSource
 */
export type AppointmentSource = "artist_manual" | "client_booking";

/**
 * AppointmentStatus
 */
export type AppointmentStatus =
  | "requested"
  | "under_review"
  | "confirmed"
  | "declined"
  | "cancelled"
  | "completed"
  | "no_show";

/**
 * AppointmentUpdate
 */
export type AppointmentUpdate = {
  /**
   * Start At
   */
  start_at?: string | null;
  /**
   * End At
   */
  end_at?: string | null;
  /**
   * Title
   */
  title?: string | null;
  status?: AppointmentStatus | null;
  /**
   * Size
   */
  size?: string | null;
  /**
   * Placement
   */
  placement?: string | null;
  color_type?: ColorType | null;
  /**
   * Subject
   */
  subject?: string | null;
  /**
   * Accommodations Notes
   */
  accommodations_notes?: string | null;
  /**
   * Has Guests
   */
  has_guests?: boolean | null;
  /**
   * Guests Notes
   */
  guests_notes?: string | null;
};

/**
 * ArtistProfileRead
 */
export type ArtistProfileRead = {
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
  /**
   * Slug
   */
  slug: string;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Business Name
   */
  business_name?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
  /**
   * Location
   */
  location?: string | null;
  /**
   * Timezone
   */
  timezone: string;
  /**
   * Instagram Handle
   */
  instagram_handle?: string | null;
  /**
   * Instagram Url
   */
  instagram_url?: string | null;
  /**
   * Deposit Default Cents
   */
  deposit_default_cents: number;
  /**
   * Require Review Before Confirm
   */
  require_review_before_confirm: boolean;
  /**
   * Accepting Bookings
   */
  accepting_bookings: boolean;
  /**
   * Booking Min Notice Minutes
   */
  booking_min_notice_minutes: number;
  /**
   * Booking Max Advance Days
   */
  booking_max_advance_days: number;
  /**
   * Default Slot Minutes
   */
  default_slot_minutes: number;
  /**
   * Buffer Minutes
   */
  buffer_minutes: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Cancellation Policy
   */
  cancellation_policy?: string | null;
  /**
   * Auto Charge Day Of
   */
  auto_charge_day_of: boolean;
  /**
   * Confirm Before Charge
   */
  confirm_before_charge: boolean;
};

/**
 * ArtistProfileUpdate
 */
export type ArtistProfileUpdate = {
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Business Name
   */
  business_name?: string | null;
  /**
   * Bio
   */
  bio?: string | null;
  /**
   * Location
   */
  location?: string | null;
  /**
   * Timezone
   */
  timezone?: string | null;
  /**
   * Instagram Handle
   */
  instagram_handle?: string | null;
  /**
   * Instagram Url
   */
  instagram_url?: string | null;
  /**
   * Deposit Default Cents
   */
  deposit_default_cents?: number | null;
  /**
   * Require Review Before Confirm
   */
  require_review_before_confirm?: boolean | null;
  /**
   * Accepting Bookings
   */
  accepting_bookings?: boolean | null;
  /**
   * Booking Min Notice Minutes
   */
  booking_min_notice_minutes?: number | null;
  /**
   * Booking Max Advance Days
   */
  booking_max_advance_days?: number | null;
  /**
   * Default Slot Minutes
   */
  default_slot_minutes?: number | null;
  /**
   * Buffer Minutes
   */
  buffer_minutes?: number | null;
  /**
   * Cancellation Policy
   */
  cancellation_policy?: string | null;
  /**
   * Auto Charge Day Of
   */
  auto_charge_day_of?: boolean | null;
  /**
   * Confirm Before Charge
   */
  confirm_before_charge?: boolean | null;
};

/**
 * AvailabilityExceptionCreate
 */
export type AvailabilityExceptionCreate = {
  /**
   * Date
   */
  date: string;
  type: AvailabilityExceptionType;
  /**
   * Start Time
   */
  start_time?: string | null;
  /**
   * End Time
   */
  end_time?: string | null;
  /**
   * Note
   */
  note?: string | null;
};

/**
 * AvailabilityExceptionRead
 */
export type AvailabilityExceptionRead = {
  /**
   * Date
   */
  date: string;
  type: AvailabilityExceptionType;
  /**
   * Start Time
   */
  start_time?: string | null;
  /**
   * End Time
   */
  end_time?: string | null;
  /**
   * Note
   */
  note?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
};

/**
 * AvailabilityExceptionType
 */
export type AvailabilityExceptionType = "custom_hours" | "closed";

/**
 * AvailabilityRuleCreate
 */
export type AvailabilityRuleCreate = {
  /**
   * Day Of Week
   */
  day_of_week: number;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * End Time
   */
  end_time: string;
  /**
   * Slot Minutes
   */
  slot_minutes?: number;
  /**
   * Effective From
   */
  effective_from?: string | null;
  /**
   * Effective To
   */
  effective_to?: string | null;
  /**
   * Is Closed
   */
  is_closed?: boolean;
};

/**
 * AvailabilityRuleRead
 */
export type AvailabilityRuleRead = {
  /**
   * Day Of Week
   */
  day_of_week: number;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * End Time
   */
  end_time: string;
  /**
   * Slot Minutes
   */
  slot_minutes?: number;
  /**
   * Effective From
   */
  effective_from?: string | null;
  /**
   * Effective To
   */
  effective_to?: string | null;
  /**
   * Is Closed
   */
  is_closed?: boolean;
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * Body_uploads-upload_image
 */
export type BodyUploadsUploadImage = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * BookingModule
 */
export type BookingModule = {
  /**
   * Key
   */
  key: string;
  /**
   * Enabled
   */
  enabled?: boolean;
};

/**
 * BookingPageRead
 */
export type BookingPageRead = {
  /**
   * Modules
   */
  modules?: Array<BookingModule> | null;
  /**
   * Draft
   */
  draft?: Array<BookingModule> | null;
  /**
   * Published
   */
  published?: boolean;
  /**
   * Announcement Banner
   */
  announcement_banner?: string | null;
  /**
   * Announcement Active
   */
  announcement_active?: boolean;
};

/**
 * BookingPageUpdate
 */
export type BookingPageUpdate = {
  /**
   * Draft
   */
  draft?: Array<BookingModule> | null;
  /**
   * Announcement Banner
   */
  announcement_banner?: string | null;
  /**
   * Announcement Active
   */
  announcement_active?: boolean | null;
  /**
   * Publish
   */
  publish?: boolean;
};

/**
 * BookingRequest
 */
export type BookingRequest = {
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
  /**
   * Client Name
   */
  client_name: string;
  /**
   * Client Email
   */
  client_email: string;
  /**
   * Client Phone
   */
  client_phone: string;
  /**
   * Size
   */
  size?: string | null;
  /**
   * Placement
   */
  placement?: string | null;
  color_type?: ColorType | null;
  /**
   * Subject
   */
  subject?: string | null;
  /**
   * Accommodations Notes
   */
  accommodations_notes?: string | null;
  /**
   * Has Guests
   */
  has_guests?: boolean;
  /**
   * Guests Notes
   */
  guests_notes?: string | null;
  /**
   * Payment Method Id
   */
  payment_method_id?: string | null;
  /**
   * Age Confirmed
   */
  age_confirmed?: boolean;
};

/**
 * BookingResult
 */
export type BookingResult = {
  /**
   * Appointment Id
   */
  appointment_id: string;
  status: AppointmentStatus;
  /**
   * Message
   */
  message: string;
};

/**
 * ButtonShape
 */
export type ButtonShape = "rounded" | "sharp";

/**
 * CampaignCreate
 */
export type CampaignCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Body
   */
  body: string;
  /**
   * Link
   */
  link?: string | null;
  channel?: MessageChannel;
  /**
   * Audience
   */
  audience?: {
    [key: string]: unknown;
  } | null;
};

/**
 * CampaignRead
 */
export type CampaignRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Body
   */
  body: string;
  /**
   * Link
   */
  link?: string | null;
  channel: MessageChannel;
  /**
   * Status
   */
  status: string;
};

/**
 * CheckoutItem
 */
export type CheckoutItem = {
  /**
   * Product Id
   */
  product_id: string;
  /**
   * Quantity
   */
  quantity: number;
};

/**
 * CheckoutRequest
 */
export type CheckoutRequest = {
  /**
   * Items
   */
  items: Array<CheckoutItem>;
  /**
   * Customer Name
   */
  customer_name: string;
  /**
   * Customer Email
   */
  customer_email: string;
  /**
   * Customer Phone
   */
  customer_phone?: string | null;
  /**
   * Shipping Address
   */
  shipping_address?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Accepted Terms
   */
  accepted_terms?: boolean;
};

/**
 * CheckoutResult
 */
export type CheckoutResult = {
  /**
   * Order Id
   */
  order_id: string;
  /**
   * Total Cents
   */
  total_cents: number;
  /**
   * Status
   */
  status: string;
  /**
   * Message
   */
  message: string;
};

/**
 * ClerkMe
 */
export type ClerkMe = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Role
   */
  role: string;
  /**
   * Slug
   */
  slug?: string | null;
};

/**
 * ClerkSync
 */
export type ClerkSync = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
};

/**
 * ColorType
 */
export type ColorType = "color" | "black_and_grey";

/**
 * ContactCreate
 */
export type ContactCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Instagram
   */
  instagram?: string | null;
  /**
   * Alt Ids
   */
  alt_ids?: {
    [key: string]: unknown;
  } | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * ContactRead
 */
export type ContactRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Instagram
   */
  instagram?: string | null;
  /**
   * Alt Ids
   */
  alt_ids?: {
    [key: string]: unknown;
  } | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * ContactUpdate
 */
export type ContactUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Instagram
   */
  instagram?: string | null;
  /**
   * Alt Ids
   */
  alt_ids?: {
    [key: string]: unknown;
  } | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * EmailCodeConfirm
 */
export type EmailCodeConfirm = {
  /**
   * Email
   */
  email: string;
  /**
   * Code
   */
  code: string;
};

/**
 * EmailCodeRequest
 */
export type EmailCodeRequest = {
  /**
   * Email
   */
  email: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * FlashPieceCreate
 */
export type FlashPieceCreate = {
  /**
   * Image Url
   */
  image_url: string;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Price Min Cents
   */
  price_min_cents?: number | null;
  /**
   * Price Max Cents
   */
  price_max_cents?: number | null;
  /**
   * Price Plus
   */
  price_plus?: boolean;
  /**
   * Size Min
   */
  size_min?: string | null;
  /**
   * Size Plus
   */
  size_plus?: boolean;
  /**
   * Ask About
   */
  ask_about?: boolean;
  /**
   * Event Tag
   */
  event_tag?: string | null;
};

/**
 * FlashPieceRead
 */
export type FlashPieceRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
  /**
   * Image Url
   */
  image_url: string;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Price Min Cents
   */
  price_min_cents?: number | null;
  /**
   * Price Max Cents
   */
  price_max_cents?: number | null;
  /**
   * Price Plus
   */
  price_plus: boolean;
  /**
   * Size Min
   */
  size_min?: string | null;
  /**
   * Size Plus
   */
  size_plus: boolean;
  /**
   * Ask About
   */
  ask_about: boolean;
  status: FlashStatus;
  /**
   * Event Tag
   */
  event_tag?: string | null;
};

/**
 * FlashPieceUpdate
 */
export type FlashPieceUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Price Min Cents
   */
  price_min_cents?: number | null;
  /**
   * Price Max Cents
   */
  price_max_cents?: number | null;
  /**
   * Price Plus
   */
  price_plus?: boolean | null;
  /**
   * Size Min
   */
  size_min?: string | null;
  /**
   * Size Plus
   */
  size_plus?: boolean | null;
  /**
   * Ask About
   */
  ask_about?: boolean | null;
  /**
   * Event Tag
   */
  event_tag?: string | null;
  status?: FlashStatus | null;
};

/**
 * FlashStatus
 */
export type FlashStatus = "available" | "claimed";

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * IssueReportCreate
 */
export type IssueReportCreate = {
  /**
   * Message
   */
  message: string;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Page
   */
  page?: string | null;
};

/**
 * IssueReportResult
 */
export type IssueReportResult = {
  /**
   * Incident Code
   */
  incident_code: string;
  /**
   * Message
   */
  message: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
};

/**
 * ItemRead
 */
export type ItemRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * LoginResult
 * Either a real bearer token, or a 2FA challenge with a short-lived preauth token.
 */
export type LoginResult = {
  /**
   * Requires 2Fa
   */
  requires_2fa?: boolean;
  /**
   * Preauth Token
   */
  preauth_token?: string | null;
  /**
   * Access Token
   */
  access_token?: string | null;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * MessageChannel
 */
export type MessageChannel = "in_app" | "sms" | "email";

/**
 * MessageResponse
 */
export type MessageResponse = {
  /**
   * Message
   */
  message: string;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
  /**
   * Items
   */
  items: Array<ItemRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * PortfolioImageCreate
 */
export type PortfolioImageCreate = {
  /**
   * Image Url
   */
  image_url: string;
  /**
   * Caption
   */
  caption?: string | null;
  /**
   * Is Healed
   */
  is_healed?: boolean;
  /**
   * Tattoo Date
   */
  tattoo_date?: string | null;
};

/**
 * PortfolioImageRead
 */
export type PortfolioImageRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
  /**
   * Image Url
   */
  image_url: string;
  /**
   * Caption
   */
  caption?: string | null;
  /**
   * Sort Order
   */
  sort_order: number;
  /**
   * Is Healed
   */
  is_healed: boolean;
  /**
   * Tattoo Date
   */
  tattoo_date?: string | null;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Price Cents
   */
  price_cents: number;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Inventory
   */
  inventory?: number | null;
  /**
   * Active
   */
  active?: boolean;
};

/**
 * ProductRead
 */
export type ProductRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Artist Id
   */
  artist_id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Price Cents
   */
  price_cents: number;
  /**
   * Images
   */
  images?: Array<string> | null;
  /**
   * Inventory
   */
  inventory?: number | null;
  /**
   * Active
   */
  active: boolean;
};

/**
 * ProductUpdate
 */
export type ProductUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Price Cents
   */
  price_cents?: number | null;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Inventory
   */
  inventory?: number | null;
  /**
   * Active
   */
  active?: boolean | null;
};

/**
 * PublicArtistRead
 */
export type PublicArtistRead = {
  /**
   * Slug
   */
  slug: string;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Bio
   */
  bio?: string | null;
  /**
   * Location
   */
  location?: string | null;
  /**
   * Instagram Url
   */
  instagram_url?: string | null;
  /**
   * Deposit Default Cents
   */
  deposit_default_cents: number;
  /**
   * Accepting Bookings
   */
  accepting_bookings: boolean;
  /**
   * Require Review Before Confirm
   */
  require_review_before_confirm: boolean;
  theme?: ThemeSettingsRead | null;
  /**
   * Announcement Banner
   */
  announcement_banner?: string | null;
  /**
   * Modules
   */
  modules?: Array<BookingModule> | null;
};

/**
 * SlotRead
 */
export type SlotRead = {
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
};

/**
 * ThemeSettingsRead
 */
export type ThemeSettingsRead = {
  /**
   * Font
   */
  font?: string | null;
  /**
   * Palette
   */
  palette?: {
    [key: string]: unknown;
  } | null;
  /**
   * Module Colors
   */
  module_colors?: {
    [key: string]: unknown;
  } | null;
  /**
   * Background Color
   */
  background_color?: string | null;
  /**
   * Background Image Url
   */
  background_image_url?: string | null;
  button_shape: ButtonShape;
  /**
   * Header Image Url
   */
  header_image_url?: string | null;
  /**
   * Center Widget Image Url
   */
  center_widget_image_url?: string | null;
  /**
   * Accents
   */
  accents?: {
    [key: string]: unknown;
  } | null;
};

/**
 * ThemeSettingsUpdate
 */
export type ThemeSettingsUpdate = {
  /**
   * Font
   */
  font?: string | null;
  /**
   * Palette
   */
  palette?: {
    [key: string]: unknown;
  } | null;
  /**
   * Module Colors
   */
  module_colors?: {
    [key: string]: unknown;
  } | null;
  /**
   * Background Color
   */
  background_color?: string | null;
  /**
   * Background Image Url
   */
  background_image_url?: string | null;
  button_shape?: ButtonShape | null;
  /**
   * Header Image Url
   */
  header_image_url?: string | null;
  /**
   * Center Widget Image Url
   */
  center_widget_image_url?: string | null;
  /**
   * Accents
   */
  accents?: {
    [key: string]: unknown;
  } | null;
};

/**
 * TotpEnrollResponse
 */
export type TotpEnrollResponse = {
  /**
   * Secret
   */
  secret: string;
  /**
   * Otpauth Uri
   */
  otpauth_uri: string;
  /**
   * Qr Svg
   */
  qr_svg: string;
};

/**
 * TotpVerifyRequest
 */
export type TotpVerifyRequest = {
  /**
   * Code
   */
  code: string;
};

/**
 * TwoFactorLoginRequest
 */
export type TwoFactorLoginRequest = {
  /**
   * Preauth Token
   */
  preauth_token: string;
  /**
   * Code
   */
  code: string;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
  /**
   * Url
   */
  url: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  role?: UserRole;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
  role?: UserRole;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Totp Enabled
   */
  totp_enabled?: boolean;
};

/**
 * UserRole
 */
export type UserRole = "artist" | "client";

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginResponse =
  AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterError =
  RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterResponse =
  RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type RequestVerificationCodeData = {
  body: EmailCodeRequest;
  path?: never;
  query?: never;
  url: "/auth/request-verification-code";
};

export type RequestVerificationCodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RequestVerificationCodeError =
  RequestVerificationCodeErrors[keyof RequestVerificationCodeErrors];

export type RequestVerificationCodeResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type RequestVerificationCodeResponse =
  RequestVerificationCodeResponses[keyof RequestVerificationCodeResponses];

export type ConfirmVerificationCodeData = {
  body: EmailCodeConfirm;
  path?: never;
  query?: never;
  url: "/auth/confirm-verification-code";
};

export type ConfirmVerificationCodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ConfirmVerificationCodeError =
  ConfirmVerificationCodeErrors[keyof ConfirmVerificationCodeErrors];

export type ConfirmVerificationCodeResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type ConfirmVerificationCodeResponse =
  ConfirmVerificationCodeResponses[keyof ConfirmVerificationCodeResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: LoginResult;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type TwoFactorLoginData = {
  body: TwoFactorLoginRequest;
  path?: never;
  query?: never;
  url: "/auth/2fa/login";
};

export type TwoFactorLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TwoFactorLoginError =
  TwoFactorLoginErrors[keyof TwoFactorLoginErrors];

export type TwoFactorLoginResponses = {
  /**
   * Successful Response
   */
  200: LoginResult;
};

export type TwoFactorLoginResponse =
  TwoFactorLoginResponses[keyof TwoFactorLoginResponses];

export type EnrollTotpData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/2fa/enroll";
};

export type EnrollTotpResponses = {
  /**
   * Successful Response
   */
  200: TotpEnrollResponse;
};

export type EnrollTotpResponse = EnrollTotpResponses[keyof EnrollTotpResponses];

export type EnableTotpData = {
  body: TotpVerifyRequest;
  path?: never;
  query?: never;
  url: "/auth/2fa/enable";
};

export type EnableTotpErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EnableTotpError = EnableTotpErrors[keyof EnableTotpErrors];

export type EnableTotpResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type EnableTotpResponse = EnableTotpResponses[keyof EnableTotpResponses];

export type DisableTotpData = {
  body: TotpVerifyRequest;
  path?: never;
  query?: never;
  url: "/auth/2fa/disable";
};

export type DisableTotpErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DisableTotpError = DisableTotpErrors[keyof DisableTotpErrors];

export type DisableTotpResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type DisableTotpResponse =
  DisableTotpResponses[keyof DisableTotpResponses];

export type ListRulesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/availability/rules";
};

export type ListRulesResponses = {
  /**
   * Response Availability-List Rules
   * Successful Response
   */
  200: Array<AvailabilityRuleRead>;
};

export type ListRulesResponse = ListRulesResponses[keyof ListRulesResponses];

export type CreateRuleData = {
  body: AvailabilityRuleCreate;
  path?: never;
  query?: never;
  url: "/availability/rules";
};

export type CreateRuleErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateRuleError = CreateRuleErrors[keyof CreateRuleErrors];

export type CreateRuleResponses = {
  /**
   * Successful Response
   */
  200: AvailabilityRuleRead;
};

export type CreateRuleResponse = CreateRuleResponses[keyof CreateRuleResponses];

export type DeleteRuleData = {
  body?: never;
  path: {
    /**
     * Rule Id
     */
    rule_id: string;
  };
  query?: never;
  url: "/availability/rules/{rule_id}";
};

export type DeleteRuleErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRuleError = DeleteRuleErrors[keyof DeleteRuleErrors];

export type DeleteRuleResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListExceptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/availability/exceptions";
};

export type ListExceptionsResponses = {
  /**
   * Response Availability-List Exceptions
   * Successful Response
   */
  200: Array<AvailabilityExceptionRead>;
};

export type ListExceptionsResponse =
  ListExceptionsResponses[keyof ListExceptionsResponses];

export type CreateExceptionData = {
  body: AvailabilityExceptionCreate;
  path?: never;
  query?: never;
  url: "/availability/exceptions";
};

export type CreateExceptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateExceptionError =
  CreateExceptionErrors[keyof CreateExceptionErrors];

export type CreateExceptionResponses = {
  /**
   * Successful Response
   */
  200: AvailabilityExceptionRead;
};

export type CreateExceptionResponse =
  CreateExceptionResponses[keyof CreateExceptionResponses];

export type DeleteExceptionData = {
  body?: never;
  path: {
    /**
     * Exception Id
     */
    exception_id: string;
  };
  query?: never;
  url: "/availability/exceptions/{exception_id}";
};

export type DeleteExceptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteExceptionError =
  DeleteExceptionErrors[keyof DeleteExceptionErrors];

export type DeleteExceptionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PreviewSlotsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date
     */
    date: string;
  };
  url: "/availability/slots";
};

export type PreviewSlotsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PreviewSlotsError = PreviewSlotsErrors[keyof PreviewSlotsErrors];

export type PreviewSlotsResponses = {
  /**
   * Response Availability-Preview Slots
   * Successful Response
   */
  200: Array<SlotRead>;
};

export type PreviewSlotsResponse =
  PreviewSlotsResponses[keyof PreviewSlotsResponses];

export type ListAppointmentsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Start
     */
    start: string;
    /**
     * End
     */
    end: string;
  };
  url: "/appointments/";
};

export type ListAppointmentsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAppointmentsError =
  ListAppointmentsErrors[keyof ListAppointmentsErrors];

export type ListAppointmentsResponses = {
  /**
   * Response Appointments-List Appointments
   * Successful Response
   */
  200: Array<AppointmentRead>;
};

export type ListAppointmentsResponse =
  ListAppointmentsResponses[keyof ListAppointmentsResponses];

export type CreateAppointmentData = {
  body: AppointmentCreate;
  path?: never;
  query?: never;
  url: "/appointments/";
};

export type CreateAppointmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAppointmentError =
  CreateAppointmentErrors[keyof CreateAppointmentErrors];

export type CreateAppointmentResponses = {
  /**
   * Successful Response
   */
  200: AppointmentRead;
};

export type CreateAppointmentResponse =
  CreateAppointmentResponses[keyof CreateAppointmentResponses];

export type DeleteAppointmentData = {
  body?: never;
  path: {
    /**
     * Appointment Id
     */
    appointment_id: string;
  };
  query?: never;
  url: "/appointments/{appointment_id}";
};

export type DeleteAppointmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAppointmentError =
  DeleteAppointmentErrors[keyof DeleteAppointmentErrors];

export type DeleteAppointmentResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAppointmentData = {
  body?: never;
  path: {
    /**
     * Appointment Id
     */
    appointment_id: string;
  };
  query?: never;
  url: "/appointments/{appointment_id}";
};

export type GetAppointmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAppointmentError =
  GetAppointmentErrors[keyof GetAppointmentErrors];

export type GetAppointmentResponses = {
  /**
   * Successful Response
   */
  200: AppointmentRead;
};

export type GetAppointmentResponse =
  GetAppointmentResponses[keyof GetAppointmentResponses];

export type UpdateAppointmentData = {
  body: AppointmentUpdate;
  path: {
    /**
     * Appointment Id
     */
    appointment_id: string;
  };
  query?: never;
  url: "/appointments/{appointment_id}";
};

export type UpdateAppointmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAppointmentError =
  UpdateAppointmentErrors[keyof UpdateAppointmentErrors];

export type UpdateAppointmentResponses = {
  /**
   * Successful Response
   */
  200: AppointmentRead;
};

export type UpdateAppointmentResponse =
  UpdateAppointmentResponses[keyof UpdateAppointmentResponses];

export type ListContactsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/contacts/";
};

export type ListContactsResponses = {
  /**
   * Response Contacts-List Contacts
   * Successful Response
   */
  200: Array<ContactRead>;
};

export type ListContactsResponse =
  ListContactsResponses[keyof ListContactsResponses];

export type CreateContactData = {
  body: ContactCreate;
  path?: never;
  query?: never;
  url: "/contacts/";
};

export type CreateContactErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateContactError = CreateContactErrors[keyof CreateContactErrors];

export type CreateContactResponses = {
  /**
   * Successful Response
   */
  200: ContactRead;
};

export type CreateContactResponse =
  CreateContactResponses[keyof CreateContactResponses];

export type DeleteContactData = {
  body?: never;
  path: {
    /**
     * Contact Id
     */
    contact_id: string;
  };
  query?: never;
  url: "/contacts/{contact_id}";
};

export type DeleteContactErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteContactError = DeleteContactErrors[keyof DeleteContactErrors];

export type DeleteContactResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateContactData = {
  body: ContactUpdate;
  path: {
    /**
     * Contact Id
     */
    contact_id: string;
  };
  query?: never;
  url: "/contacts/{contact_id}";
};

export type UpdateContactErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateContactError = UpdateContactErrors[keyof UpdateContactErrors];

export type UpdateContactResponses = {
  /**
   * Successful Response
   */
  200: ContactRead;
};

export type UpdateContactResponse =
  UpdateContactResponses[keyof UpdateContactResponses];

export type GetMyProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/profile/me";
};

export type GetMyProfileResponses = {
  /**
   * Successful Response
   */
  200: ArtistProfileRead;
};

export type GetMyProfileResponse =
  GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdateMyProfileData = {
  body: ArtistProfileUpdate;
  path?: never;
  query?: never;
  url: "/profile/me";
};

export type UpdateMyProfileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMyProfileError =
  UpdateMyProfileErrors[keyof UpdateMyProfileErrors];

export type UpdateMyProfileResponses = {
  /**
   * Successful Response
   */
  200: ArtistProfileRead;
};

export type UpdateMyProfileResponse =
  UpdateMyProfileResponses[keyof UpdateMyProfileResponses];

export type GetThemeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/profile/theme";
};

export type GetThemeResponses = {
  /**
   * Successful Response
   */
  200: ThemeSettingsRead;
};

export type GetThemeResponse = GetThemeResponses[keyof GetThemeResponses];

export type UpdateThemeData = {
  body: ThemeSettingsUpdate;
  path?: never;
  query?: never;
  url: "/profile/theme";
};

export type UpdateThemeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateThemeError = UpdateThemeErrors[keyof UpdateThemeErrors];

export type UpdateThemeResponses = {
  /**
   * Successful Response
   */
  200: ThemeSettingsRead;
};

export type UpdateThemeResponse =
  UpdateThemeResponses[keyof UpdateThemeResponses];

export type GetPublicArtistData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/public/artists/{slug}";
};

export type GetPublicArtistErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublicArtistError =
  GetPublicArtistErrors[keyof GetPublicArtistErrors];

export type GetPublicArtistResponses = {
  /**
   * Successful Response
   */
  200: PublicArtistRead;
};

export type GetPublicArtistResponse =
  GetPublicArtistResponses[keyof GetPublicArtistResponses];

export type GetPublicPortfolioData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/public/artists/{slug}/portfolio";
};

export type GetPublicPortfolioErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublicPortfolioError =
  GetPublicPortfolioErrors[keyof GetPublicPortfolioErrors];

export type GetPublicPortfolioResponses = {
  /**
   * Response Public-Get Public Portfolio
   * Successful Response
   */
  200: Array<PortfolioImageRead>;
};

export type GetPublicPortfolioResponse =
  GetPublicPortfolioResponses[keyof GetPublicPortfolioResponses];

export type GetPublicProductsData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/public/artists/{slug}/products";
};

export type GetPublicProductsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublicProductsError =
  GetPublicProductsErrors[keyof GetPublicProductsErrors];

export type GetPublicProductsResponses = {
  /**
   * Response Public-Get Public Products
   * Successful Response
   */
  200: Array<ProductRead>;
};

export type GetPublicProductsResponse =
  GetPublicProductsResponses[keyof GetPublicProductsResponses];

export type CheckoutData = {
  body: CheckoutRequest;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/public/artists/{slug}/checkout";
};

export type CheckoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CheckoutError = CheckoutErrors[keyof CheckoutErrors];

export type CheckoutResponses = {
  /**
   * Successful Response
   */
  200: CheckoutResult;
};

export type CheckoutResponse = CheckoutResponses[keyof CheckoutResponses];

export type GetPublicFlashData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/public/artists/{slug}/flash";
};

export type GetPublicFlashErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublicFlashError =
  GetPublicFlashErrors[keyof GetPublicFlashErrors];

export type GetPublicFlashResponses = {
  /**
   * Response Public-Get Public Flash
   * Successful Response
   */
  200: Array<FlashPieceRead>;
};

export type GetPublicFlashResponse =
  GetPublicFlashResponses[keyof GetPublicFlashResponses];

export type GetPublicSlotsData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query: {
    /**
     * Date
     */
    date: string;
  };
  url: "/public/artists/{slug}/slots";
};

export type GetPublicSlotsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublicSlotsError =
  GetPublicSlotsErrors[keyof GetPublicSlotsErrors];

export type GetPublicSlotsResponses = {
  /**
   * Response Public-Get Public Slots
   * Successful Response
   */
  200: Array<SlotRead>;
};

export type GetPublicSlotsResponse =
  GetPublicSlotsResponses[keyof GetPublicSlotsResponses];

export type BookData = {
  body: BookingRequest;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/public/artists/{slug}/book";
};

export type BookErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BookError = BookErrors[keyof BookErrors];

export type BookResponses = {
  /**
   * Successful Response
   */
  200: BookingResult;
};

export type BookResponse = BookResponses[keyof BookResponses];

export type ClerkMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/clerk/me";
};

export type ClerkMeResponses = {
  /**
   * Successful Response
   */
  200: ClerkMe;
};

export type ClerkMeResponse = ClerkMeResponses[keyof ClerkMeResponses];

export type ClerkSyncData = {
  body: ClerkSync;
  path?: never;
  query?: never;
  url: "/clerk/sync";
};

export type ClerkSyncErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClerkSyncError = ClerkSyncErrors[keyof ClerkSyncErrors];

export type ClerkSyncResponses = {
  /**
   * Successful Response
   */
  200: ClerkMe;
};

export type ClerkSyncResponse = ClerkSyncResponses[keyof ClerkSyncResponses];

export type UploadImageData = {
  body: BodyUploadsUploadImage;
  path?: never;
  query?: never;
  url: "/uploads/image";
};

export type UploadImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
  /**
   * Successful Response
   */
  200: UploadResponse;
};

export type UploadImageResponse =
  UploadImageResponses[keyof UploadImageResponses];

export type ListPortfolioData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/portfolio/";
};

export type ListPortfolioResponses = {
  /**
   * Response Portfolio-List Portfolio
   * Successful Response
   */
  200: Array<PortfolioImageRead>;
};

export type ListPortfolioResponse =
  ListPortfolioResponses[keyof ListPortfolioResponses];

export type CreatePortfolioImageData = {
  body: PortfolioImageCreate;
  path?: never;
  query?: never;
  url: "/portfolio/";
};

export type CreatePortfolioImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePortfolioImageError =
  CreatePortfolioImageErrors[keyof CreatePortfolioImageErrors];

export type CreatePortfolioImageResponses = {
  /**
   * Successful Response
   */
  200: PortfolioImageRead;
};

export type CreatePortfolioImageResponse =
  CreatePortfolioImageResponses[keyof CreatePortfolioImageResponses];

export type DeletePortfolioImageData = {
  body?: never;
  path: {
    /**
     * Image Id
     */
    image_id: string;
  };
  query?: never;
  url: "/portfolio/{image_id}";
};

export type DeletePortfolioImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePortfolioImageError =
  DeletePortfolioImageErrors[keyof DeletePortfolioImageErrors];

export type DeletePortfolioImageResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListFlashData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/flash/";
};

export type ListFlashResponses = {
  /**
   * Response Flash-List Flash
   * Successful Response
   */
  200: Array<FlashPieceRead>;
};

export type ListFlashResponse = ListFlashResponses[keyof ListFlashResponses];

export type CreateFlashData = {
  body: FlashPieceCreate;
  path?: never;
  query?: never;
  url: "/flash/";
};

export type CreateFlashErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFlashError = CreateFlashErrors[keyof CreateFlashErrors];

export type CreateFlashResponses = {
  /**
   * Successful Response
   */
  200: FlashPieceRead;
};

export type CreateFlashResponse =
  CreateFlashResponses[keyof CreateFlashResponses];

export type DeleteFlashData = {
  body?: never;
  path: {
    /**
     * Piece Id
     */
    piece_id: string;
  };
  query?: never;
  url: "/flash/{piece_id}";
};

export type DeleteFlashErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFlashError = DeleteFlashErrors[keyof DeleteFlashErrors];

export type DeleteFlashResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateFlashData = {
  body: FlashPieceUpdate;
  path: {
    /**
     * Piece Id
     */
    piece_id: string;
  };
  query?: never;
  url: "/flash/{piece_id}";
};

export type UpdateFlashErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFlashError = UpdateFlashErrors[keyof UpdateFlashErrors];

export type UpdateFlashResponses = {
  /**
   * Successful Response
   */
  200: FlashPieceRead;
};

export type UpdateFlashResponse =
  UpdateFlashResponses[keyof UpdateFlashResponses];

export type ListProductsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products/";
};

export type ListProductsResponses = {
  /**
   * Response Products-List Products
   * Successful Response
   */
  200: Array<ProductRead>;
};

export type ListProductsResponse =
  ListProductsResponses[keyof ListProductsResponses];

export type CreateProductData = {
  body: ProductCreate;
  path?: never;
  query?: never;
  url: "/products/";
};

export type CreateProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
  /**
   * Successful Response
   */
  200: ProductRead;
};

export type CreateProductResponse =
  CreateProductResponses[keyof CreateProductResponses];

export type DeleteProductData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: string;
  };
  query?: never;
  url: "/products/{product_id}";
};

export type DeleteProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteProductError = DeleteProductErrors[keyof DeleteProductErrors];

export type DeleteProductResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateProductData = {
  body: ProductUpdate;
  path: {
    /**
     * Product Id
     */
    product_id: string;
  };
  query?: never;
  url: "/products/{product_id}";
};

export type UpdateProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
  /**
   * Successful Response
   */
  200: ProductRead;
};

export type UpdateProductResponse =
  UpdateProductResponses[keyof UpdateProductResponses];

export type GetLayoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/booking-page/";
};

export type GetLayoutResponses = {
  /**
   * Successful Response
   */
  200: BookingPageRead;
};

export type GetLayoutResponse = GetLayoutResponses[keyof GetLayoutResponses];

export type UpdateLayoutData = {
  body: BookingPageUpdate;
  path?: never;
  query?: never;
  url: "/booking-page/";
};

export type UpdateLayoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateLayoutError = UpdateLayoutErrors[keyof UpdateLayoutErrors];

export type UpdateLayoutResponses = {
  /**
   * Successful Response
   */
  200: BookingPageRead;
};

export type UpdateLayoutResponse =
  UpdateLayoutResponses[keyof UpdateLayoutResponses];

export type ListCampaignsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/campaigns/";
};

export type ListCampaignsResponses = {
  /**
   * Response Campaigns-List Campaigns
   * Successful Response
   */
  200: Array<CampaignRead>;
};

export type ListCampaignsResponse =
  ListCampaignsResponses[keyof ListCampaignsResponses];

export type CreateCampaignData = {
  body: CampaignCreate;
  path?: never;
  query?: never;
  url: "/campaigns/";
};

export type CreateCampaignErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCampaignError =
  CreateCampaignErrors[keyof CreateCampaignErrors];

export type CreateCampaignResponses = {
  /**
   * Successful Response
   */
  200: CampaignRead;
};

export type CreateCampaignResponse =
  CreateCampaignResponses[keyof CreateCampaignResponses];

export type DeleteCampaignData = {
  body?: never;
  path: {
    /**
     * Campaign Id
     */
    campaign_id: string;
  };
  query?: never;
  url: "/campaigns/{campaign_id}";
};

export type DeleteCampaignErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCampaignError =
  DeleteCampaignErrors[keyof DeleteCampaignErrors];

export type DeleteCampaignResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReportIssueData = {
  body: IssueReportCreate;
  path?: never;
  query?: never;
  url: "/issues/";
};

export type ReportIssueErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReportIssueError = ReportIssueErrors[keyof ReportIssueErrors];

export type ReportIssueResponses = {
  /**
   * Successful Response
   */
  200: IssueReportResult;
};

export type ReportIssueResponse =
  ReportIssueResponses[keyof ReportIssueResponses];

export type ReadItemData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/items/";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: PageItemRead;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type CreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemRead;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/items/{item_id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};
