"""add clerk_sub to user

Revision ID: 31e617fd8677
Revises: 4c25566c0cd1
Create Date: 2026-06-16 21:03:29.122050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31e617fd8677"
down_revision: Union[str, None] = "4c25566c0cd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("clerk_sub", sa.String(), nullable=True))
    op.create_index(op.f("ix_user_clerk_sub"), "user", ["clerk_sub"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_clerk_sub"), table_name="user")
    op.drop_column("user", "clerk_sub")
    # ### end Alembic commands ###
