"""flashbook core schema

Revision ID: 4c25566c0cd1
Revises: b389592974f8
Create Date: 2026-06-16 19:56:29.479330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c25566c0cd1'
down_revision: Union[str, None] = 'b389592974f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmetic_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_asset_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['cosmetic_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('deposit_default_cents', sa.Integer(), nullable=False),
    sa.Column('require_review_before_confirm', sa.Boolean(), nullable=False),
    sa.Column('accepting_bookings', sa.Boolean(), nullable=False),
    sa.Column('booking_min_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('booking_max_advance_days', sa.Integer(), nullable=False),
    sa.Column('default_slot_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('auto_charge_day_of', sa.Boolean(), nullable=False),
    sa.Column('confirm_before_charge', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_artist_profiles_slug'), 'artist_profiles', ['slug'], unique=True)
    op.create_table('assistant_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_artist_id', sa.UUID(), nullable=False),
    sa.Column('assistant_user_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('custom_hours', 'closed', name='availabilityexceptiontype', native_enum=False), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_page_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('announcement_banner', sa.Text(), nullable=True),
    sa.Column('announcement_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.Enum('in_app', 'sms', 'email', name='messagechannel', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'sent', name='campaignstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('alt_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('connect_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('stripe_account_id', sa.String(), nullable=False),
    sa.Column('charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('alt_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_client_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['linked_client_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('artist_client', 'dm', 'shop_group', name='conversationtype', native_enum=False), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flash_pieces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_min_cents', sa.Integer(), nullable=True),
    sa.Column('price_max_cents', sa.Integer(), nullable=True),
    sa.Column('price_plus', sa.Boolean(), nullable=False),
    sa.Column('size_min', sa.String(), nullable=True),
    sa.Column('size_plus', sa.Boolean(), nullable=False),
    sa.Column('ask_about', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('available', 'claimed', name='flashstatus', native_enum=False), nullable=False),
    sa.Column('event_tag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_healed', sa.Boolean(), nullable=False),
    sa.Column('tattoo_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('percent', 'fixed', name='promotype', native_enum=False), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.Enum('booking', 'merch', 'both', name='promoappliesto', native_enum=False), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('monthly', 'annual', name='subscriptionplan', native_enum=False), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_table('theme_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('font', sa.String(), nullable=True),
    sa.Column('palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('module_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('background_image_url', sa.String(), nullable=True),
    sa.Column('button_shape', sa.Enum('rounded', 'sharp', name='buttonshape', native_enum=False), nullable=False),
    sa.Column('header_image_url', sa.String(), nullable=True),
    sa.Column('center_widget_image_url', sa.String(), nullable=True),
    sa.Column('accents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('waivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['artist_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'artist_id')
    )
    op.create_table('booths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['artist_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'sms', 'email', name='messagechannel', native_enum=False), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_pm_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('last4', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('client_user_id', sa.UUID(), nullable=True),
    sa.Column('booth_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('requested', 'under_review', 'confirmed', 'declined', 'cancelled', 'completed', 'no_show', name='appointmentstatus', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('artist_manual', 'client_booking', name='appointmentsource', native_enum=False), nullable=False),
    sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('color_type', sa.Enum('color', 'black_and_grey', name='colortype', native_enum=False), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('accommodations_notes', sa.Text(), nullable=True),
    sa.Column('has_guests', sa.Boolean(), nullable=False),
    sa.Column('guests_notes', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('client_phone', sa.String(), nullable=True),
    sa.Column('deposit_cents', sa.Integer(), nullable=False),
    sa.Column('deposit_status', sa.Enum('none', 'pending', 'authorized', 'paid', 'refunded', 'failed', name='depositstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.ForeignKeyConstraint(['client_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booth_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booth_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booth_id', 'artist_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('deposit', 'balance', 'day_of', name='paymentkind', native_enum=False), nullable=False),
    sa.Column('method', sa.Enum('card', 'cash', name='paymentmethodtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('healed_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signed_waivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waiver_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('signer_name', sa.String(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('age_verified', sa.Boolean(), nullable=False),
    sa.Column('health_questionnaire', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['waiver_id'], ['waivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role', sa.Enum('artist', 'client', name='userrole', native_enum=False), nullable=False))
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('user', sa.Column('totp_enabled', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'totp_secret')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'role')
    op.drop_table('signed_waivers')
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('booth_members')
    op.drop_table('appointments')
    op.drop_table('payment_methods')
    op.drop_table('order_items')
    op.drop_table('messages')
    op.drop_table('conversation_participants')
    op.drop_table('cart_items')
    op.drop_table('booths')
    op.drop_table('artist_group_members')
    op.drop_table('waivers')
    op.drop_table('theme_settings')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_table('products')
    op.drop_table('portfolio_images')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_table('flash_pieces')
    op.drop_table('email_verification_codes')
    op.drop_table('conversations')
    op.drop_table('contacts')
    op.drop_table('connect_accounts')
    op.drop_table('client_profiles')
    op.drop_table('carts')
    op.drop_table('campaigns')
    op.drop_table('booking_page_layouts')
    op.drop_table('availability_rules')
    op.drop_table('availability_exceptions')
    op.drop_table('audit_logs')
    op.drop_table('assistant_grants')
    op.drop_index(op.f('ix_artist_profiles_slug'), table_name='artist_profiles')
    op.drop_table('artist_profiles')
    op.drop_table('artist_groups')
    op.drop_table('artist_asset_purchases')
    op.drop_table('cosmetic_assets')
    # ### end Alembic commands ###
