"""issue reports

Revision ID: 649cfb1273a5
Revises: eb8920d6ffc6
Create Date: 2026-06-17 00:32:07.550167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "649cfb1273a5"
down_revision: Union[str, None] = "eb8920d6ffc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_code", sa.String(), nullable=False),
        sa.Column("reporter_role", sa.String(), nullable=False),
        sa.Column("reporter_user_id", sa.UUID(), nullable=True),
        sa.Column("reporter_email", sa.String(), nullable=True),
        sa.Column("page", sa.String(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issue_reports_incident_code"),
        "issue_reports",
        ["incident_code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_reports_incident_code"), table_name="issue_reports")
    op.drop_table("issue_reports")
    # ### end Alembic commands ###
