"""order customer + terms fields

Revision ID: eb8920d6ffc6
Revises: 31e617fd8677
Create Date: 2026-06-16 23:49:40.984211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'eb8920d6ffc6'
down_revision: Union[str, None] = '31e617fd8677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('accepted_terms', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('accepted_terms_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'accepted_terms_at')
    op.drop_column('orders', 'accepted_terms')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
